name: Deploy Angular App to S3 and Amplify

on:
  push:
    branches:
      - main  # Altere para o branch principal do seu repositório

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build -- --configuration production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Cancel pending or running jobs in Amplify
        run: |
          jobs=$(aws amplify list-jobs --app-id ${{ secrets.AMPLIFY_APP_ID }} --branch-name main --query 'jobs[?status==`PENDING` || status==`RUNNING`].jobId' --output text)
          for job_id in $jobs; do
            echo "Canceling job with job-id: $job_id"
            aws amplify stop-job --app-id ${{ secrets.AMPLIFY_APP_ID }} --branch-name main --job-id $job_id
          done

      - name: Deploy to S3
        run: |
          aws s3 sync dist/book-wise s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Deploy to Amplify
        run: |
          aws amplify start-job --app-id ${{ secrets.AMPLIFY_APP_ID }} --branch-name main --job-type RELEASE
