name: Deploy Angular App to S3 and Amplify

on:
  push:
    branches:
      - main  # Altere para o branch principal do seu repositório

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build -- --configuration production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync dist/book-wise s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Verify jq installation
        run: |
          jq --version

      - name: Cancel previous Amplify deployments
        run: |
          echo "Verificando jobs em andamento..."
          for attempt in {1..5}; do
            JOBS=$(aws amplify list-jobs \
              --app-id ${{ secrets.AMPLIFY_APP_ID }} \
              --branch-name main \
              --query 'jobSummaries[?status==`PENDING` || status==`RUNNING`].jobId' \
              --output text)

            if [ -z "$JOBS" ]; then
              echo "Nenhum job em execução."
              break
            fi

            echo "Encontrado(s) job(s) pendente(s): $JOBS"
            for JOB_ID in $JOBS; do
              echo "Cancelando job $JOB_ID..."
              aws amplify stop-job \
                --app-id ${{ secrets.AMPLIFY_APP_ID }} \
                --branch-name main \
                --job-id $JOB_ID
            done

            echo "Aguardando 5 segundos para verificar novamente..."
            sleep 5
          done

          # Verificar novamente após aguardar
          FINAL_JOBS=$(aws amplify list-jobs \
            --app-id ${{ secrets.AMPLIFY_APP_ID }} \
            --branch-name main \
            --query 'jobSummaries[?status==`PENDING` || status==`RUNNING`].jobId' \
            --output text)

          if [ -n "$FINAL_JOBS" ]; then
            echo "Erro: Ainda existem jobs em execução. Cancelamento falhou."
            exit 1
          fi

          echo "Todos os jobs pendentes foram cancelados com sucesso."

      - name: Update Amplify Build Settings
        run: |
          aws amplify update-branch \
            --app-id ${{ secrets.AMPLIFY_APP_ID }} \
            --branch-name main \
            --framework "Angular" \
            --enable-auto-build

      - name: Create Amplify Deployment
        id: create_deployment
        run: |
          echo "Criando novo deployment..."
          DEPLOYMENT_OUTPUT=$(aws amplify create-deployment \
            --app-id ${{ secrets.AMPLIFY_APP_ID }} \
            --branch-name main \
            --output json)

          JOB_ID=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.jobId')
          ZIP_UPLOAD_URL=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.zipUploadUrl')

          echo "JOB_ID=$JOB_ID" >> $GITHUB_ENV
          echo "ZIP_UPLOAD_URL=$ZIP_UPLOAD_URL" >> $GITHUB_ENV
          echo "Deployment criado com sucesso. JOB_ID: $JOB_ID"

      - name: Upload Artifacts to Amplify
        run: |
          zip -r deploy.zip dist/book-wise
          curl -X PUT -H "Content-Type: application/zip" \
            --data-binary @deploy.zip \
            "${{ env.ZIP_UPLOAD_URL }}"

      - name: Start Amplify Deployment
        run: |
          echo "Iniciando deployment no Amplify..."
          aws amplify start-deployment \
            --app-id ${{ secrets.AMPLIFY_APP_ID }} \
            --branch-name main \
            --job-id ${{ env.JOB_ID }}
          echo "Deployment iniciado."

